export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';
